export const ADD_WRONG_QUESTION="ADD_WRONG_QUESTION";
export const RESET_WRONG_QUESTION="RESET_WRONG_QUESTION";
export const INCREASE_SCORE="INCREASE_SCORE";
export const RESET_SCORE="RESET_SCORE";
export const TOTAL_QUESTION="TOTAL_QUESTION";